### ISSUE TITLE
0.7.x branch broken due to dependency on retriable >= 1.4

### ISSUE THREAD

**Issue by elyscape** [google/google-api-ruby-client#193]
Retriable 2.0.0 hit release today, breaking API compatibility and dropping support for Ruby 1.8. Unfortunately, the 0.7 branch of google-api-client has a dependency set for `retriable >= 1.4`, so new installs on Ruby 1.8 are broken. This was fixed in bb9f607c. Please consider cherry-picking that commit into the 0.7 branch and making a new release. Thank you.

**Comment by jeremyhaile** [comment]
I wish the dependency on retriable was just removed here.  I know it's convenient for the API developers but it's annoying for users because we want to use retriable 2.0+ and this gem is preventing us from upgrading.

Retriable is a small enough amount of code that it should probably just be replicated within this gem if necessary - and removed as a dependency.
