### ISSUE TITLE
Support Rails 4

### ISSUE THREAD

**Issue by cbeer** [google/google-api-ruby-client#209]
In f008d518f04b5619c26af0d532b8ee98344e6ae0, the requirement for `activesupport` was changed to remove support for Rails 4. We were happily using this gem with Rails 4, so I wonder if this was possibly a mistake?

**Comment by benpetro** [comment]
This has also broken my app: 
Rails 4.2
gem 'google-api-client', require: 'google/api_client'

ERROR: `require': cannot load such file -- google/api_client (LoadError)

I've had to revert back to 0.8.2 to fix it: 
gem 'google-api-client', '0.8.2', require: 'google/api_client'

**Comment by tbetbetbe** [comment]
Sorry, that change was intentional - I was trying to cleanup the dependency
specifications, clearly the new spec is wrong.

Before I fix correct this, can you see any reason why

>= 3.2

would be preferred to

~> 4.2

?

On 26 March 2015 at 23:53, Ben Petro <notifications@github.com> wrote:

> This has also broken my app:
> Rails 4.2
> gem 'google-api-client', require: 'google/api_client'
>
> ERROR: `require': cannot load such file -- google/api_client (LoadError)
>
> I've had to revert back to 0.8.2 to fix it:
> gem 'google-api-client', '0.8.2', require: 'google/api_client'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-ruby-client/issues/209#issuecomment-86847441>
> .
>



-- 
This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else (it may
contain confidential or privileged information), please erase all copies of
it, including all attachments, and please let the sender know it went to
the wrong person. Thanks.

**Comment by cbeer** [comment]
@tbetbetbe I think github markup garbled your question. 

Are you asking about why `>= 3.2` is better than `~> 3.2`, or whether this client should require Rails 4?

It seems like this gem should be able to support both Rails 3.2 and Rails 4.x, right? Or, it seemed like that was working fine before.

I've offered https://github.com/google/google-api-ruby-client/pull/211 as my preferred solution to this.

**Comment by javierjulio** [comment]
@cbeer I'm with you. I've been using this gem successfully in Rails 4 for over a year now.

**Comment by cbeer** [comment]
Fixed by #211
