### ISSUE TITLE
Unable to use version 0.8.2 along with appnexusapi gem

### ISSUE THREAD

**Issue by veerababu-nyros** [google/google-api-ruby-client#216]
I am getting gem dependency issues with multi_json and faraday while installing google-api-client latest version in my application which is already using appnexusapi gem. Is there any alternative to use both gems with in same application ( google-api-client version >= 0.8 )?

**Comment by sqrrrl** [comment]
Looks like appnexusapi is on some very old versions of those two gems. There are issues with pre 0.9 versions of Faraday that break the client, and they're at least 4 minor versions behind on multi_json.

Anyway, new version of this library drops Faraday, but the multi_json issue will still persist. Suggest contacting the appnexusapi maintainer and ask them to update their dependencies since they're further behind.
