### ISSUE TITLE
YouTube upload example for 0.9

### ISSUE THREAD

**Issue by jeffheifetz** [google/google-api-ruby-client#302]
Is there a sample/example for the 0.9 API, I can't seem to get it working. I've tried several variations of the code below.

```
  def upload!
    youtube = authenticated_service
    youtube.insert_video(metadata, upload_source: @file_path, content_type: 'video/mp4',
                                              options: { retries: 3 })
  end

  def authenticated_service
    youtube = Google::Apis::YoutubeV3::YouTubeService.new
    youtube.authorization = Signet::OAuth2::Client.new(access_token: @access_token)
    youtube
  end

  def metadata
    {
      'snippet' => {
        'title' => @title,
        'description' => @description,
        'tags' => @tags.try(:split, ',')
      },
      'status' => {
        'privacyStatus' => @privacy_status
      }
    }
  end
```

**Comment by sqrrrl** [comment]
What error do you get?

At first look, it's likely the metadata. The client uses [generated ruby types for request/response objects](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/youtube_v3/classes.rb). Hashes are also permitted as a shortcut, but the expectation is that the keys mirror the properties of the corresponding objects. These names sometimes differ from the underlying JSON structure -- e.g. snake instead of camel case, modified to avoid conflicts with built-in methods, etc. That, and symbols are used instead of strings.

This is explained in the [README file under the heading 'hashes'](https://github.com/google/google-api-ruby-client#hashes).

So while I haven't tried your code, using something like the following should get you closer:

```ruby
def metadata
  {
    :snippet => {
      :title => @title,
      :description => @description,
      :tags => @tags.try(:split, ',')
    },
    :status => {
      :privacy_status => @privacy_status
    }
  }
end
```

**Comment by jeffheifetz** [comment]
I actually get a `TypeError: Can't convert Hash into String.` whether I have the metadata symbolized or not. 

I traced it to where the metadata is attempted to be put into the url (https://github.com/google/google-api-ruby-client/blob/master/lib/google/apis/core/http_command.rb#L139). I thought it was related to the hash being nested in the `part` but I wasn't sure how else to submit the metadata.

**Comment by sqrrrl** [comment]
Ah, first param is a string, 2nd is the actual body/hash

https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/youtube_v3/service.rb#L3657

The docs from that are autogenerated from the published API definition and it's missing a definition of the actual valid values. But you can [find them in the reference docs for the youtube API](https://developers.google.com/youtube/v3/docs/videos/insert).

For your case:

```ruby
youtube.insert_video('snippet,status', 
                     metadata, 
                     upload_source: @file_path, content_type: 'video/mp4',
                     options: { retries: 3 })

**Comment by sqrrrl** [comment]
I added a simple youtube sample in the samples directory. Hope that helps.
