### ISSUE TITLE
Ruby API client doesn't follow Semantic Versioning

### ISSUE THREAD

**Issue by Temikus** [google/google-api-ruby-client#346]
I know I'm a little bit late to the party, but:

Rubygems team urges developers to follow follow [Semantic Versioning](http://semver.org/)
The first basic principle is:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 1. MAJOR version when you make incompatible API changes,

And people depend on that pattern while locking gemfiles, etc.

However, the library very clearly broke the pattern with 0.8 -> 0.9 move.
I know this has already happened, but ask you to either reconsider the versioning or at least keep this noted when doing future upgrades.

/CC @erjohnso @mbrukman

**Comment by sqrrrl** [comment]
Please note [item 4 in semver](http://semver.org/#spec-item-4):
 
"Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable."

**Comment by sqrrrl** [comment]
That said, I am looking to bump this to 1.x in the near future so that folks *can* rely on the API being stable...

**Comment by Temikus** [comment]
@sqrrrl I admit you're right on that point. 

However, please do keep in mind that this project has been alive for 5 years. A lot of projects are already using this api library to maintain their core functionality with Google services, like fog, chef, puppet and a large [number of others](https://rubygems.org/api/v1/gems/google-api-client/reverse_dependencies.json).

This is somewhat worsened by the fact that people are getting a bit used to 4th clause violations, thanks to gems like [mysql2](https://github.com/brianmario/mysql2) (which practically everyone uses with Rails if they have mysql backing) which is still at `0.4.2` while being used in production stacks.

**Comment by sqrrrl** [comment]
I understand, that's the primary reason why it was left in preview for 6 months. My initial inclination was to fork at the time since there wasn't much we could do with versions. Going to 1.0 would have been premature at the time, so that either meant breaking people when the version changed or releasing under a new gem name so the two versions wouldn't conflict (which has it's own issues..). After some internal discussion it was decided to just go ahead and break things.
