### ISSUE TITLE
How to implement google analytic's  api ?

### ISSUE THREAD

**Issue by fahimbabarpatel** [google/google-api-ruby-client#352]
Hello,

I followed https://github.com/google/google-api-ruby-client . 

Readme have good code for google drive
```
require 'google/apis/drive_v2'

Drive = Google::Apis::DriveV2 # Alias the module
drive = Drive::DriveService.new

NOT UNDERSTOOD below line

drive.authorization = authorization # See Googleauth or Signet libraries

```

I setup all required items like google project, created p12 file, given permission to user.

Now for implementing GA, I am not getting proper steps from start end.

Please guide.

Thanks!

**Comment by fahimbabarpatel** [comment]
@sqrrrl Can you please look into this. Gem is already in Alpha mode. Should I continue with ruby or switch to other stable technology library.

**Comment by sqrrrl** [comment]
You can consider the gem more stable at this point than alpha. I don't anticipate any major changes and will try to get this to 1.0 and call it stable in the near future.

As for authorization, the reasons it's a placeholder in samples like that is because it depends on the context.

Since you mentioned P12, I take it you're using a service account. In that case, you'll have code that looks like:

```ruby
analytics.authorization = Google::Auth.get_application_default(Google::Apis::AnalyticsV3::AUTH_ANALYTICS)
```

That does require two things different on your end though:

* Use a JSON key instead of P12.
* Set the environment variable GOOGLE_APPLICATION_CREDENTIALS to the path of the JSON key file.

See I'd suggest looking at https://developers.google.com/identity/protocols/application-default-credentials for more.

There's a sample dir in this project that shows a few different APIs (including analytics) as well as different auth methods (service accounts, user credentials from the command line, a web app, etc.) Take a look.

**Comment by fahimbabarpatel** [comment]
@sqrrrl  Thanks! lot for reply.

Will ping in the case of help.

**Comment by fahimbabarpatel** [comment]
@sqrrrl 

When I hit below code:-

**service.list_account_summaries**

Then get below error:-

**Google::Apis::ClientError: insufficientPermissions: Insufficient Permission**

When I hit below code and it work fine give proper result.
```
profile_id = 'ga:12345678'

start_date = '2015-10-01'

end_date = '2016-02-12'

metrics = 'ga:sessions'

service.get_ga_data(profile_id, start_date, end_date, metrics, {
  dimensions: 'ga:date'
})
```


Please let me know why **list_account_summaries** failing ?

Thanks!

**Comment by fahimbabarpatel** [comment]
@sqrrrl  Can you please reply on above comment ..

**Comment by sqrrrl** [comment]
That error means what it says -- the credentials you're using don't have permission to have access that profile.

If you're using a service account, did you authorize that account to access your data in Analytics? Are you using the correct ID for the profile/view?

I'm not that familiar with the analytics API, so you might wan to try [this question on stack overflow](http://stackoverflow.com/questions/14525565/not-sufficient-permissions-google-analytics-api-service-account) for various things to check.

**Comment by fahimbabarpatel** [comment]
Thanks! for reply @sqrrrl
