### ISSUE TITLE
Requiring schema for Marshaling data 0.8

### ISSUE THREAD

**Issue by jhblacklock** [google/google-api-ruby-client#381]
I am storing returns in redis and loading such data results in an undefined Class error.  Since the schemas are dynamically loaded how can I require the class beforehand so Ruby has the definition of the class loaded and can create an instance of it?

I am using version 0.8.

**Comment by sqrrrl** [comment]
You're probably better off handling the marshaling to/from hashes or JSON yourself.

Even better is to update to 0.9.x which uses ahead-of-time code generation instead of generating things dynamically at runtime. Even then, I'd still recommend handling marshaling yourself if you're going to persist in redis.

**Comment by jhblacklock** [comment]
Thanks much!  Done and done.
