### ISSUE TITLE
Cannot watch a Gmail user for new messages

### ISSUE THREAD

**Issue by MasterRoot24** [google/google-api-ruby-client#383]
I'm trying to get my app notified of new messages in a specific user's Gmail mailbox. I'm trying to use the method `Google::Apis::GmailV1::GmailService.watch_user()` to do this.

I currently have the following code:

```
def authorise
  # Do some stuff to get credentials; not important here
end

service = Google::Apis::GmailV1::GmailService.new
service.client_options.application_name = APPLICATION_NAME
service.authorization = authorise

watch_request = Google::Apis::GmailV1::WatchRequest.new
watch_request.topic_name = 'projects/my_project/topics/push'

service.watch_user('me', watch_request) do |request|
  while true
    request.update! unless Time.at(request.expiration.to_i / 1000) > Time.now
  end
end
```

This works and no errors are thrown. Problem is, I have no idea from the documentation and from the code in this gem what to do to be notified about new messages in the mailbox.

Can someone help please?

**Comment by sqrrrl** [comment]
In the future, please direct "how-to" questions to stackoverflow.

Since you set up the subscription to push messages to a topic, to get the notifications you need to [subscribe and pull messages](https://cloud.google.com/pubsub/overview).  

While there is a separate gcloud ruby library, you can also use pubsub from this API if you don't want a separate dependency. See [this example](https://github.com/google/google-api-ruby-client/blob/master/samples/cli/lib/samples/pubsub.rb#L93).

See https://developers.google.com/gmail/api/guides/push for more.

**Comment by MasterRoot24** [comment]
@sqrrrl I should have mentioned in my original message that I had already asked this message on StackOverflow [here](http://stackoverflow.com/q/36190210/1788943), but received no answers. This felt like the next best place to ask for help, given the maturity of the gem and it still being in alpha.

If Stack Overflow is the place that you want new users to go to for help using this gem, then maybe that should be highlighted in the README.

**Comment by JoeNyland** [comment]
@utiq No, I gave up trying to watch for messages using this gem and resorted to polling on an configurable interval. Not ideal, but it got the job done.

It's not great, but here's my code if it helps: https://github.com/JoeNyland/gmail-slack-notifier/blob/master/exe/gmail-slack-notifier.rb

**Comment by utiq** [comment]
Oh ok, well, I figured out how to do it but using push instead of trying to pull. I did it using your same code but a different configuration in the topic and subscription.
