### ISSUE TITLE
How should Fog-Google deal with version > 0.9

### ISSUE THREAD

**Issue by icco** [google/google-api-ruby-client#384]
Hi there @sqrrrl. I'm working on https://github.com/fog/fog-google/pull/100. Fog-Google is a wrapper around a bunch of Google APIs.

Reading https://github.com/google/google-api-ruby-client/blob/5ec8d9c75cd68d9bd0139cf808c4ac2d2d86cd57/MIGRATING.md, it is unclear what will happen when I require `"google/api_client"` like I do at https://github.com/icco/fog-google/blob/upgrade-google-api-client/lib/fog/google.rb#L72-L78. Does this mean I don't have to require any of the sub API versions later? 

What was the decision behind moving away from API Discovery support?

**Comment by sqrrrl** [comment]
Nope, including google/api_client won't load any of the generated interfaces. You'll still need to pull in the ones you're actually using.

As for why the switch from runtime code generation to ahead of time, it was mostly around usability & performance. If the previous client were just a dumb http client with oauth support, it wouldn't have been so bad. But it wasn't. The runtime code generation did inflections on the request bodies & responses, inconsistently at that (request/response bodies, but not params...and even then, there were exceptions...) And since it was all done at runtime, there were little in documentation to show what the right call was.. It was just a bunch of arbitrary rules that users needed to understand. And based on the # of "how do I..." bugs, people didn't.. And there were at least 3 or 4 different calling styles supported which also didn't make things any clearer...

That, and there were a lot of performance issues with how it was implemented. Excessive invalidations of the method cache, plus it required developers to do extra work to do the right thing and cache discovery docs...

Most of that goes away with ahead of time generation. No extra lookups for discovery, no need to think about caching api descriptions, no guessing what a call looks like any more...

All that said, there's still a generic 'http' method on BaseService if you just want to treat the client as a slightly smarter HTTP client with oauth support & retries...

And since everything still is generated from discovery, there are things that could be done if absolutely needed. I'm not too keen on supporting multiple calling styles again, but it would be possible to add a generic `execute` in the 0.8.x style. It would be too hard and confusing to be 100% compatible with 0.8.x, but a subset of functionality could be restored.
