### ISSUE TITLE
Status 429 (Too many requests) raises `ClientError`

### ISSUE THREAD

**Issue by coreyward** [google/google-api-ruby-client#445]
According to your documentation…

> [Google::Apis::ClientError] The request is invalid and should not be retried without modification

However, I get a `Google::Apis::ClientError` with the message `Invalid request` when the status code returned by Hurley is 429 (which corresponds to too many requests). In this case, the request can and should be retried without modification, just later.

A more appropriate error class would be helpful in diagnosing this problem for others in the future.

Thanks.

**Comment by sqrrrl** [comment]
Which API is returning the 429 error? And do you have the body of the response?
Right now the client is looking for specific error strings (rateLimitExceeded userRateLimitExceeded) since not all the APIs are consistent about which error code to use for rate limit errors. But it's easy enough to add support for specific codes too.

Anyway, if you can provide some details I can update the error handling logic to account for it.

**Comment by coreyward** [comment]
Accessing the Drive API (scope: `https://www.googleapis.com/auth/drive`). Happens across a number of requests when working with documents through https://github.com/gimite/google-drive-ruby.

**Comment by sqrrrl** [comment]
Will be in the 0.10 release.
