### ISSUE TITLE
SDK Design 

### ISSUE THREAD

**Issue by zotherstupidguy** [google/google-api-ruby-client#460]
While I was trying to test google APIs via ruby SDK, I found it VERY VERY difficult to get something up and running even after going through the various online documentations. Obviously the services provided are indeed complex and done by various teams. However still getting something done via the Ruby SDK is not as sweet as other Ruby SDKs naturally are! I am under the impression that this was NOT done by ruby developers but rather via a very talented team whose language of choice for day to day operations is NOT ruby! (smells like Java)

Kindly please be aware that more syntactic sugar is indeed needed to make those amazing services actually usable by the community at a larger scale. In my opinion more emphasis on the SDK's interfaces design is urgently needed. 

Please share your thoughts...

**Comment by zotherstupidguy** [comment]
An example of a Ruby developer normal expectation
`
 myfile = Google::Apis::DriveV3::File.new do 
original_filename = "originalnamemyfile"
description = "mydescription"
name = "myfilename"
end  
`

This doesn't work!

**Comment by sqrrrl** [comment]
Happy to add additional sugar to make things easier where needed. Yielding in the initializer is easy enough to do.

FYI, there is some sugar in there already for the example you provided - e.g. you can just pass properties in as keyword args:

```
myfile = Google::Apis::DriveV3::File.new( 
  original_filename : "originalnamemyfile"
  description:  "mydescription"
  name:  "myfilename"
)  
```
And can just use vanilla hashes instead of using the actual types too..

If you have specific things you'd like, please file issues or send PRs. Have to be careful about things that break the API, but small bits of sugar are fine.

Anyway, I'm going to close this as it's a little too broad of an issue and not really actionable.

**Comment by zotherstupidguy** [comment]
@sqrrrl Thank you for the hints. 

I beg to differ regarding being careful about breaking the SDK interface, as I find that is exactly what is needed here (bundler would takecare of older versions). I can't think of a better way of collecting some opinions about what "should" the SDK design be. And as ruby has no unified style of doing things, to avoid going on circles it would be better to get a taste of what other like\dislike too.

**Comment by sqrrrl** [comment]
To clarify, the short term goal right now is to get to a stable 1.0 release. Significant design changes that break compatibility outside what is planned for 0.10 are off the table right now. *After* that, if there are ideas on what a 2.0 should look like I'm happy to entertain them.
