### ISSUE TITLE
allow active_support (and thus rails) 5

### ISSUE THREAD

**Issue by mattknox** [google/google-api-ruby-client#465]
I'm pretty sure rails 5 works for us with 0.9.11, we use gcs, speech, calendars and contacts.   I didn't see anything 0.9.11->0.9.13 that looked scary wrt recent activesupport.

**Comment by sqrrrl** [comment]
It is allowed on 9.x. There's no long a runtime dependency on activesupport. Are you seeing a particular issue?

0.8.x was recently locked down to activesupport < 5. Mostly it's because:

* No work planned for the 0.8.x line nor plans to ensure it works with newer versions of rails.
* The version specifier was a little too loose and caught a lot of apps by surprise, particularly since activesupport 5 requires ruby >=2.2.2.

**Comment by mattknox** [comment]
I was referring to https://github.com/google/google-api-ruby-client/blob/master/Gemfile, where for development at least, you limit to activesupport < 5.  But that's not a runtime dep, it seems.  All's well, then!
