### ISSUE TITLE
Invalid documentation for GmailService #send_user_message

### ISSUE THREAD

**Issue by bittrance** [google/google-api-ruby-client#474]
Class Message says about raw:

``` ruby
        # The entire email message in an RFC 2822 formatted and base64url encoded string.
        # Returned in messages.get and drafts.get responses when the format=RAW
        # parameter is supplied.
        # Corresponds to the JSON property `raw`
        # @return [String]
        attr_accessor :raw
```

However, I succeed using this method only if I send a RFC2822 string that is not base64-encoded.

**Comment by sqrrrl** [comment]
Yeah, this is a bit confusing and affects multiple client libraries. The problem is the issue is describing the underlying JSON/HTTP protocol, but the client libraries handle a lot of details like base64 encoding.

I can update the generator to add a comment for base64 encoded fields that the encoding is done automatically.

**Comment by dklanac** [comment]
+1 for updating the generator. I was shaking my head until I found this ticket. All good now that I left the Base64 stuff to the client to handle.
