### ISSUE TITLE
Any way to make a dry run in 0.9 ??

### ISSUE THREAD

**Issue by gmarco** [google/google-api-ruby-client#476]
Hi

in 0.8 it was possible to do with the same r/w login a dry run f.e. for batch deletes, to see what will be deleted.

in 0.9 i did not find any way for thay , except do the delete direct and see what was deleted.

in 0.8 i was simple done by 

`  res=client.execute(
        :api_method => ad.users.aliases.delete,
       :authenticated => false
`

it would be nice to have this in 0.9 too

**Comment by sqrrrl** [comment]
That wasn't ever a designed/supported feature in 0.8 either.

If you want to do what you did in 0.8 where you just run the request without credentials, you can do that too -- the request options allow you to pass in per-request credentials. Just set them to something invalid and the request will fail.

In either case, it's not a terribly useful thing to do since the auth error would mask everything and the only meaningful feedback would be from the debug output.
