### ISSUE TITLE
Hurley vs Faraday

### ISSUE THREAD

**Issue by sesam** [google/google-api-ruby-client#518]
What was the rationale in 0.9pre1 for replacing Faraday with Hurley?

That rationaly may now have changed, see:
https://github.com/lostisland/hurley
"GitHub - lostisland/hurley: DEAD project, don't use"

Most recommendations (also from Hurley dev) point to keeping using Faraday. Or kill your dependencies!

**Comment by hamadata** [comment]
Just a memo, though:
On v0.9, http client switched from Faraday to Hurley.  
https://github.com/google/google-api-ruby-client/commit/f584a2cec862169fc2005b16f028dc548336301d#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR5

**Comment by sesam** [comment]
Hamadasan Thanks for the link :). That commit looks like a mix of several commits, so maybe it was exported from Googles internal version tool and just pasted in.

**Comment by sqrrrl** [comment]
There were a few reasons:

* Lack of streaming support in Faraday.
* Very long release cycles/waiting for critical updates. Old library had a bunch of monkey patches to work around bugs (e.g. improper query parameter encoding) in Faraday.
* Pluggable transports == more things that break/need testing.

Hurley, at the time, fixed a bunch of the issues we had with Faraday. But it was quickly abandoned by the author. Since Faraday is still an issue for various reasons, ended up settling on HttpClient. It's mature and stable and has the features we need.
