### ISSUE TITLE
Batch request in google API doesnt work. Fails with too many concurrent connections

### ISSUE THREAD

**Issue by we138** [google/google-api-ruby-client#616]
I am working with google analytics service and I need to get some reports from analytics reporting API, but I stumbled upon a problem with `#batch `feature:
```
pages = %s(home contacts profile ...)  # array of pages for which i want to get reports
reports = []

client.batch do |client|
  pages.each do |page|
    report = build_report(page)        # build report object for each page
    client.batch_get_reports(GetReportsRequest.new(report_requests: [report])) do |res, _|
      reports << result
    end
  end
end
```

but I get in response too much reports with errors:
`D, [2017-08-31T14:03:05.014508 #23097] DEBUG -- : Error - #<Google::Apis::RateLimitError: rateLimitExceeded: Quota Error: profileId 12345 has too many concurrent connections.>`

why I got it? because I'm doing one big batch request and it shouldnt be concurrent, no?

I found that issue https://github.com/google/google-api-ruby-client/issues/210 and @sqrrrl  says:

> Use smaller batches :)

but my batch has about 100 elements, where is even smaller :)

**Comment by sqrrrl** [comment]
See https://developers.google.com/analytics/devguides/reporting/core/v4/help for getting help with analytics API.

To clarify, when you're using client.batch those requests are executed concurrently once they hit the server. So if analytics doesn't like you making 100 concurrent requests then you'll need to do smaller batches.

Also note that batch_get_reports *also* supports a type of batching, albeit with some constraints. But if you read the docs, you'll notice that there's a limit of 5 reports per batch. I don't know if that's constrained by processing/concurrent connection limits or the potential response size, but it does suggest that you'll likely need to throttle yourself closer to that # than the current ~100 or so that you have now.

**Comment by we138** [comment]
@sqrrrl ok, thank you
