### ISSUE TITLE
Your documentation, such as it is, is just wrong

### ISSUE THREAD

**Issue by nello** [google/google-api-ruby-client#617]
For a couple of days now, I've been trying to use this library to do the incredibly simple task of renaming a file. I've tried using snippets of code based on your README, and they basically just explode.

Everything in the 'Hashes' section is wrong. For instance:

    file = Drive::File.new(id: '123', title: 'My document')
    file.labels = Drive::File::Labels.new(starred: true)
    file = drive.update_file(file) # Returns a Drive::File instance

Gives:
    TypeError: Can't convert Google::Apis::DriveV3::File into String or Array.

Looking at the code, update_file expects a file_id as its first param. Every example has the same kind of issues.

How DO I use this library to rename a file? It's frankly beyond me.

**Comment by architapatelis** [comment]
@nello I did some testing, in order to update the name of an existing file I had my google drive, I did this:

1. In order to take care of the authorization part, I set up a Ruby command line application by following these directions - https://developers.google.com/drive/v3/web/quickstart/ruby

2. `list_files` will allow you to look up the relevant `file_id`

3. use `update_file` in order to update the `name` key or any other metadata. 

Link that you will find useful - https://developers.google.com/drive/v3/web/integrate-create#create_a_new_file_from_the_drive_ui

```ruby
# Initialize the API
service = Google::Apis::DriveV3::DriveService.new
service.client_options.application_name = APPLICATION_NAME
service.authorization = authorize

# List the 10 most recently modified files.
response = service.list_files(page_size: 10,
                              fields: 'nextPageToken, files(id, name)')
puts 'Files:'
puts 'No files found' if response.files.empty?
response.files.each do |file|
  puts "#{file.name} (#{file.id})"
end

file_id = 'YOURFILEIDGOESHERE'
file_metadata = {
    modified_time: DateTime.now,
    name: "Google API for Ruby"
}
file = service.update_file(file_id,
                                 file_metadata,
                                 fields: 'id, modifiedTime, name')
puts "Modified time: #{file.modified_time}" #=> Modified time: 2017-10-06T06:35:09+00:00
puts "Modified name: #{file.name}" #=> Modified name: Google API for Ruby

```

If you intend on testing out the google drive api like I did (i.e. by setting up command line), you will need to make one change in the `quickstart.rb` file. You will need to change the scope from `readonly` to `drive`, in order to gain full access - read more about it here - https://developers.google.com/drive/v2/web/about-auth

```ruby 
SCOPE = Google::Apis::DriveV3::AUTH_DRIVE_METADATA_READONLY
#change it to:
SCOPE = Google::Apis::DriveV3::AUTH_DRIVE

```
hope this helps!

**Comment by nello** [comment]
@architapatelis thanks for taking the time to help out!

I did get file renaming working eventually, but it was a bad ride. All the obvious things fail, for example getting hold of a file_id for an existing file from the API then calling `#update_file` with a new name will give: `Google::Apis::ClientError: fieldNotWritable: The resource body includes fields which are not directly writable.`

The **only** thing that worked for me was to create a brand new `File` object with minimal fields and use it as a vector for the rename:

`def rename_file(file_id, name)
        drive.update_file(file_id, Google::Apis::DriveV3::File.new(name: name))
end`

The README file currently associated with this project really needs to be deleted and started again. :(

**Comment by mattwhisenhunt** [comment]
@nello sorry to hear about your doc ride. I agree we need to point towards API reference docs every chance we get, I find wonderful little gems in them all the time.
